import os
import sys
import json
from logger import logger
from config import Config
from instagram_publisher import publish_media, publish_story

def main():
    """
    Step 2: Instagram Publishing (Runs after GitHub Pages deployment)
    Reads the metadata generated by main.py and triggers Graph API.
    """
    try:
        logger.info("Starting Step 2: Instagram Publishing")
        
        # 1. Validate Environment variables
        Config.validate()
        
        # 2. Read metadata generated by main.py
        metadata_path = os.path.join("output", "post_metadata.json")
        if not os.path.exists(metadata_path):
            raise FileNotFoundError(f"Metadata file {metadata_path} not found. Did main.py run successfully?")
            
        with open(metadata_path, 'r', encoding='utf-8') as f:
            metadata = json.load(f)
            
        video_url = metadata.get("video_url")
        caption = metadata.get("caption")
        
        if not video_url or not caption:
            raise ValueError("Invalid metadata. Missing video_url or caption.")
            
        logger.info(f"Loaded public URL: {video_url}")
        
        # 3. Publish to Instagram
        post_id = publish_media(video_url, caption)
        
        logger.info(f"Successfully published Instagram REEL with ID: {post_id}")
        
        # 4. Publish to Instagram Stories (DISABLED - Moved to dedicated image story pipeline)
        # logger.info("Starting Step 2b: Instagram Story Publishing")
        # try:
        #     story_id = publish_story(video_url)
        #     logger.info(f"Successfully published Instagram STORY with ID: {story_id}")
        # except Exception as e:
        #     logger.error(f"Story publishing failed, but Reel was successful: {e}")
        #     # We don't exit(1) here because the primary REEL was successful.
        
    except Exception as e:
        logger.error(f"Publishing failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
